# Site settings
title: Godot MMORPG Documentation
description: Technical documentation, Game Design, Art Bible, and Audio Bible for the Godot MMORPG Project
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections for organizing documentation
collections:
  technical:
    output: true
    permalink: /:collection/:name
  gamedesign:
    output: true
    permalink: /:collection/:name
  artbible:
    output: true
    permalink: /:collection/:name
  audiobible:
    output: true
    permalink: /:collection/:name

# Default front matter
defaults:
  - scope:
      path: ""
      type: "technical"
    values:
      layout: "page"
      category: "Technical Documentation"
  - scope:
      path: ""
      type: "gamedesign"
    values:
      layout: "page"
      category: "Game Design Documentation"
  - scope:
      path: ""
      type: "artbible"
    values:
      layout: "page"
      category: "Art Bible Documentation"
  - scope:
      path: ""
      type: "audiobible"
    values:
      layout: "page"
      category: "Audio Bible Documentation"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
