name: Preview Branch Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]
  # push:
  #   branches-ignore:
  #     - main

permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  build-preview:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: static-site-source/package-lock.json

      - name: Install dependencies
        run: cd static-site-source && npm ci

      - name: Get branch name
        id: branch-name
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "branch=${{ github.head_ref }}" >> $GITHUB_OUTPUT
            echo "pr_number=${{ github.event.number }}" >> $GITHUB_OUTPUT
          else
            echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          fi

      - name: Build preview with branch-specific base path
        run: cd static-site-source && npm run build
        env:
          NODE_ENV: production
          NEXT_PUBLIC_BASE_PATH: /docs/preview/${{ steps.branch-name.outputs.branch }}

      - name: Sanitize branch name
        id: sanitized-branch-name
        run: |
          sanitized="$(echo "${{ steps.branch-name.outputs.branch }}" | sed 's#[^a-zA-Z0-9._-]#-#g')"
          echo "value=$sanitized" >> $GITHUB_OUTPUT

      - name: Upload preview artifact
        uses: actions/upload-artifact@v4
        with:
          name: preview-${{ steps.sanitized-branch-name.outputs.value }}
          path: ./static-site-source/out
          retention-days: 7

      - name: Comment on PR with preview info
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const branchName = '${{ steps.branch-name.outputs.branch }}';
            const runId = '${{ github.run_id }}';
            const body = `## 🚀 Preview Build Complete
            
            Your branch preview has been built successfully!
            
            **Branch:** \`${branchName}\`
            **Artifacts:** [Download preview build](https://github.com/${{ github.repository }}/actions/runs/${runId})
            
            You can download the preview artifact and test it locally:
            1. Download the artifact from the link above
            2. Extract the files
            3. Serve locally with: \`npx serve -s ./out\`
            
            > **Note:** This is a preview build artifact. To deploy this preview to a live URL, you would need to set up a preview deployment service like Netlify, Vercel, or Cloudflare Pages.`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });

      - name: Set commit status
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: '${{ github.event.pull_request.head.sha }}',
              state: 'success',
              target_url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}',
              description: 'Preview build available for download',
              context: 'preview/build'
            });
