name: Preview Branch Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  statuses: write
  pages: write
  id-token: write

concurrency:
  group: preview-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build-preview:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: static-site-source/package-lock.json

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: cd static-site-source && npm ci

      - name: Get branch name
        id: branch-name
        run: |
          echo "branch=${{ github.head_ref }}" >> $GITHUB_OUTPUT
          echo "pr_number=${{ github.event.number }}" >> $GITHUB_OUTPUT

      - name: Sanitize branch name
        id: sanitized-branch-name
        run: |
          sanitized="$(echo "${{ steps.branch-name.outputs.branch }}" | sed 's#[^a-zA-Z0-9._-]#-#g')"
          echo "value=$sanitized" >> $GITHUB_OUTPUT

      - name: Build preview
        run: cd static-site-source && npm run build
        env:
          NODE_ENV: production

      - name: Upload preview artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./static-site-source/out

  deploy-preview:
    environment:
      name: github-pages-preview
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-preview
    
    steps:
      - name: Deploy to GitHub Pages Preview Environment
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Comment on PR with preview info
        uses: actions/github-script@v7
        with:
          script: |
            const branchName = '${{ github.head_ref }}';
            const previewUrl = '${{ steps.deployment.outputs.page_url }}';
            const body = `## 🚀 Preview Deployment Complete
            
            Your branch preview has been deployed to the GitHub Pages preview environment!
            
            **Branch:** \`${branchName}\`
            **Preview URL:** ${previewUrl}
            
            > **Note:** This preview deployment temporarily replaces the main site at the GitHub Pages URL. The main site will be restored when the PR is merged or closed.
            >
            > To view this specific preview, visit the URL above. Be aware that only one preview can be active at a time.`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });

      - name: Set commit status
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: '${{ github.event.pull_request.head.sha }}',
              state: 'success',
              target_url: '${{ steps.deployment.outputs.page_url }}',
              description: 'Preview deployed to GitHub Pages',
              context: 'preview/deployment'
            });
